DTC2154801010010/Models/GiayChiTiet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTC2154801010010.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiayChiTiet
    {
        public int id { get; set; }
        public string TenGiay { get; set; }
        public string Mau { get; set; }
        public int Soluong { get; set; }
        public decimal Gia { get; set; }
        public int TTGiay { get; set; }
    
        public virtual ThongTinGiay ThongTinGiay { get; set; }
    }
}

DTC2154801010010/Controllers/GiayChiTietsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DTC2154801010010.Models
{
    public class GiayChiTietsController : Controller
    {
        private BanGiayEntities1 db = new BanGiayEntities1();

        // GET: GiayChiTiets
        public ActionResult Index()
        {
            var giayChiTiet = db.GiayChiTiet.Include(g => g.ThongTinGiay);
            return View(giayChiTiet.ToList());
        }

        // GET: GiayChiTiets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiayChiTiet giayChiTiet = db.GiayChiTiet.Find(id);
            if (giayChiTiet == null)
            {
                return HttpNotFound();
            }
            return View(giayChiTiet);
        }

        // GET: GiayChiTiets/Create
        public ActionResult Create()
        {
            ViewBag.TTGiay = new SelectList(db.ThongTinGiay, "TTGiay", "Loai");
            return View();
        }

        // POST: GiayChiTiets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,TenGiay,Mau,Soluong,Gia,TTGiay")] GiayChiTiet giayChiTiet)
        {
            // Kiểm tra tính hợp lệ của số lượng
            if (giayChiTiet.Soluong <= 0)
            {
                ModelState.AddModelError("Soluong", "Số lượng phải là số tự nhiên (nguyên dương).");
            }

            if (ModelState.IsValid)
            {
                db.GiayChiTiet.Add(giayChiTiet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TTGiay = new SelectList(db.ThongTinGiay, "TTGiay", "Loai", giayChiTiet.TTGiay);
            return View(giayChiTiet);
        }

        // GET: GiayChiTiets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiayChiTiet giayChiTiet = db.GiayChiTiet.Find(id);
            if (giayChiTiet == null)
            {
                return HttpNotFound();
            }
            ViewBag.TTGiay = new SelectList(db.ThongTinGiay, "TTGiay", "Loai", giayChiTiet.TTGiay);
            return View(giayChiTiet);
        }

        // POST: GiayChiTiets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,TenGiay,Mau,Soluong,Gia,TTGiay")] GiayChiTiet giayChiTiet)
        {
            // Kiểm tra tính hợp lệ của số lượng
            if (giayChiTiet.Soluong <= 0)
            {
                ModelState.AddModelError("Soluong", "Số lượng phải là số tự nhiên (nguyên dương).");
            }

            if (ModelState.IsValid)
            {
                db.Entry(giayChiTiet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TTGiay = new SelectList(db.ThongTinGiay, "TTGiay", "Loai", giayChiTiet.TTGiay);
            return View(giayChiTiet);
        }    


        // GET: GiayChiTiets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiayChiTiet giayChiTiet = db.GiayChiTiet.Find(id);
            if (giayChiTiet == null)
            {
                return HttpNotFound();
            }
            return View(giayChiTiet);
        }

        // POST: GiayChiTiets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GiayChiTiet giayChiTiet = db.GiayChiTiet.Find(id);
            db.GiayChiTiet.Remove(giayChiTiet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Search(string searchString)
        {
            var giayChiTiet = from g in db.GiayChiTiet
                              select g;

            if (!String.IsNullOrEmpty(searchString))
            {
                giayChiTiet = giayChiTiet.Where(s => s.TenGiay.Contains(searchString));
            }

            return View("Index", giayChiTiet.ToList());
        }
    }
}

DTC2154801010010/Views/GiayChiTiets/Create.cshtml
@model DTC2154801010010.Models.GiayChiTiet

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
   

    <div class="form-horizontal">
        <h4>GiayChiTiet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenGiay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenGiay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenGiay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TTGiay, "TTGiay", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TTGiay", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TTGiay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DTC2154801010010/Views/GiayChiTiets/Delete.cshtml
@model DTC2154801010010.Models.GiayChiTiet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GiayChiTiet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenGiay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenGiay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinGiay.Loai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinGiay.Loai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DTC2154801010010/Views/GiayChiTiets/Details.cshtml
@model DTC2154801010010.Models.GiayChiTiet

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>GiayChiTiet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenGiay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenGiay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinGiay.Loai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinGiay.Loai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DTC2154801010010/Views/GiayChiTiets/Edit.cshtml
@model DTC2154801010010.Models.GiayChiTiet

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GiayChiTiet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.TenGiay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenGiay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenGiay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TTGiay, "TTGiay", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TTGiay", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TTGiay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DTC2154801010010/Views/GiayChiTiets/Index.cshtml
@model IEnumerable<DTC2154801010010.Models.GiayChiTiet>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenGiay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Soluong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThongTinGiay.Loai)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenGiay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Soluong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThongTinGiay.Loai)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>
@using (Html.BeginForm("Search", "GiayChiTiets", FormMethod.Get))
{
    <div class="form-group">
        <label for="searchString">Tìm kiếm theo tên giày:</label>
        @Html.TextBox("searchString", Request.QueryString["searchString"], new { @class = "form-control" })
        <input type="submit" value="Tìm kiếm" class="btn btn-primary" />
    </div>
}